Revert commits that don't build on master. (#1221)
Revert "Prove compilation lemma for memcpy. TODO: needs cleanup"

This reverts commit cb6a5f7621503ff9cf05223e910d57dc9c3c8c7b.

Revert "Update to match felem spec and mostly implement memcpy lemma"

This reverts commit 245d8fe64ec8143c0abf1f22a357f3eeff735c02.

Revert "Update spec to use felems"

This reverts commit dd949789cdc38511bd12641cd5133a6cde3588f1.

Errors with
```
Error: Cannot find a physical path bound to logical path
Rupicola.Examples.Loops.
```

Maybe the submodule needs to be updated?

Please don't push commits that don't build on master, it breaks Coq's
CI.