Rework argument parsing, add --tight-bounds-mul-by
The `--tight-bounds-mul-by` argument allows us to specify the tight
bounds multiplier manually.

Closes #800
Closes #796 (actually, this had already been implemented, though we now
use it for curve25519)
Closes #755 (machine_wordsize is now owned by the binary as a whole)

Note that the last of these necessitates moving machine_wordsize to come
right after curve_description.  Invoking the binaries in the old way may
result in them hanging for a long time while they try to compute
representations for, say, lists of 2^255-19 5-bit-limbs for the "prime"
64.

We now use a structured language to describe the command line arguments,
based on OCaml's Arg module interface.  The error and help messages are
now perhaps a tiny bit worse, but it should now be moderately easier to
add new optional command line arguments.

Note that named arguments now use spaces rather than equals signs to
pass values.

The old usage message:
```
USAGE: ./src/ExtractionOCaml/unsaturated_solinas [--lang=LANGUAGE] [--static] [--internal-static] [--no-wide-int] [--widen-carry] [--widen-bytes] [--no-select] [--split-multiret] [--no-primitives] [--cmovznz-by-mul] curve_description n s-c machine_wordsize [function_to_synthesize*]
Got 0 arguments.

  LANGUAGE                The output language code should be emitted in.  Defaults to C if no language is given.  Case-sensitive.
                            Valid options are: C, Rust, Go, Java
  --static                Declare the functions as static, i.e., local to the file.
  --internal-static       Declare internal functions as static, i.e., local to the file.
  --no-wide-int           Don't use integers wider than the bitwidth.
  --widen-carry           Widen carry bit integer types to either the byte type, or to the full bitwidth if --widen-bytes is also passed.
  --widen-bytes           Widen byte types to the full bitwidth.
  --no-select             Use expressions that don't require cmov.
  --split-multiret        Don't allow instructions to return two results. This should always be set for bedrock2.
  --no-primitives         Suppress the generation of the bodies of primitive operations such as addcarryx, subborrowx, cmovznz, mulx, etc.
  --cmovznz-by-mul        Use an alternative implementation of cmovznz using multiplication rather than bitwise-and with -1.
  curve_description       A string which will be prefixed to every function name generated
  n                       The number of limbs, or the literal '(auto)' or '(autoN)' for a non-negative number N, to automatically guess the number of limbs
  s-c                     The prime, which must be expressed as a difference of a power of two and a small field element (e.g., '2^255 - 19', '2^448 - 2^224 - 1')
  machine_wordsize        The machine bitwidth (e.g., 32 or 64)
  function_to_synthesize  A space-separated list of functions that should be synthesized.  If no functions are given, all functions are synthesized.
                            Valid options are carry_mul, carry_square, carry, add, sub, opp, selectznz, to_bytes, from_bytes, or 'carry_scmul' followed by a decimal literal

Fatal error: exception Failure("Synthesis failed")
```

The new usage message:
```
./src/ExtractionOCaml/unsaturated_solinas: option 'curve_description' needs an argument.

USAGE: ./src/ExtractionOCaml/unsaturated_solinas [OPTS...] curve_description machine_wordsize n s-c [function_to_synthesize...]

  --lang {C|Rust|Go|Java}  The output language code should be emitted in.  Defaults to C if no language is given.  Case-sensitive.
  --static                 Declare the functions as static, i.e., local to the file.
  --internal-static        Declare internal functions as static, i.e., local to the file.
  --no-wide-int            Don't use integers wider than the bitwidth.
  --widen-carry            Widen carry bit integer types to either the byte type, or to the full bitwidth if --widen-bytes is also passed.
  --widen-bytes            Widen byte types to the full bitwidth.
  --no-select              Use expressions that don't require cmov.
  --split-multiret         Don't allow instructions to return two results. This should always be set for bedrock2.
  --no-primitives          Suppress the generation of the bodies of primitive operations such as addcarryx, subborrowx, cmovznz, mulx, etc.
  --cmovznz-by-mul         Use an alternative implementation of cmovznz using multiplication rather than bitwise-and with -1.
  --only-signed            Only allow signed integer types.
  --tight-bounds-mul-by    The (improper) fraction by which the (tight) bounds of each limb are scaled
  -h, --help               Display this list of options
  curve_description        A string which will be prefixed to every function name generated
  machine_wordsize         The machine bitwidth (e.g., 32 or 64)
  n                        The number of limbs, or the literal '(auto)' or '(autoN)' for a non-negative number N, to automatically guess the number of limbs
  s-c                      The prime, which must be expressed as a difference of a power of two and a small field element (e.g., '2^255 - 19', '2^448 - 2^224 - 1')
  function_to_synthesize   A space-separated list of functions that should be synthesized.  If no functions are given, all functions are synthesized.
                           Valid options are carry_mul, carry_square, carry, add, sub, opp, selectznz, to_bytes, from_bytes, or 'carry_scmul' followed by a decimal literal.

Fatal error: exception Failure("Synthesis failed")
```